### ISSUE TITLE
Latest Sort Error

### ISSUE THREAD

**Issue by kewool** [Truth-baobab-tree/TruthChromeExtension#2]
![캡처](https://user-images.githubusercontent.com/57829426/98425553-e01db480-20d8-11eb-860f-1e1a6667593d.PNG)
Even if the date is updated, it is not sorted in the most recent order.

**Comment by KHJcode** [comment]
The existing planning intent is to prevent users from modifying their ratings.
Modified and distributed by web server and extension.

Thank you for reporting.
